### ISSUE TITLE
no error triggered but no result

### ISSUE THREAD

**Issue by rafipiccolo** [Mangopay/mangopay2-nodejs-sdk#60] opened 2017-04-11 21:18 UTC
hello,

when i set this config it works.
    clientId: 'firstIdXXX',
    clientPassword: 'passphraseXXX',

and when i set this (prod), it doesn't work, and it doesn't fail => no return at all.
    clientId: 'prodIdXXX',
    clientPassword: 'prodPassphraseXXX',
    baseUrl: 'https://api.mangopay.com/'

can you ehelp me ?

this is my sample code :

var mangopay = require('mangopay2-nodejs-sdk');

var api = new mangopay({
    clientId: 'xxxx',
    clientPassword: 'xxxxx',
});

api.Users.getNatural('11510910021zx', function(result) {
    // no return
    console.log('result1', result);
})
.catch(function(data) {
    // no failure
    console.error('err', data.Message);
});

**Comment by rafipiccolo** [comment] 2017-04-11 21:32
i also tried to edit api.js in node_modules to search the bug... the explaination...

it seems that i get a 401 response code at line 176:
`if (response.statusCode === 401) {`

but the autorize call nevers returns 
`self.authorize(function(){`

**Comment by gabriellupu** [comment] 2017-04-11 21:36
Hello @rafipiccolo. Can you please debug the message and the requested URL for me please? Thanks!

**Comment by rafipiccolo** [comment] 2017-04-11 21:38
hello, where can i find it ? I dont really understand code in that lib.

**Comment by gabriellupu** [comment] 2017-04-11 21:40
You can use `debugMode` option to true so that you can have the requests and responses logged into the console: https://github.com/Mangopay/mangopay2-nodejs-sdk#supported-options

**Comment by rafipiccolo** [comment] 2017-04-11 21:44
{ '0': 'users_getnaturals',
  '1':
   { headers:
      { 'Content-Type': 'application/json',
        'User-Agent': 'MangoPay V2 Nodejs/1.4.3',
        Authorization: 'undefined undefined' },
     requestConfig: { timeout: 30000 },
     responseConfig: { timeout: 80000 },
     path:
      { id: '11510910021zx',
        clientId: 'rafipiccolo',
        apiVersion: 'v2.01' },
     dataClass: { [Function] extend: [Function], __super__: [Object] } } }

**Comment by gabriellupu** [comment] 2017-04-11 21:46
There seems to be something wrong with the Authorization header: `Authorization: 'undefined undefined'` are you sure the client is instantiated correctly?

**Comment by rafipiccolo** [comment] 2017-04-11 21:54
this si my only code.

var mangopay = require('mangopay2-nodejs-sdk');

var api = new mangopay({
clientId: 'xxxx',
clientPassword: 'xxxxx',
});

api.Users.getNatural('11510910021zx', function(result) {
// no return
console.log('result1', result);
})
.catch(function(data) {
// no failure
console.error('err', data.Message);
});

**Comment by rafipiccolo** [comment] 2017-04-12 08:38
do you see something inapropriate in my code ?
to install your lib i just did : npm install mangopay2-nodejs-sdk
is this the way u use it ?

maybe the fact is that my passprase is wrong ? my network is failing ? but whatever... can i have an explaination of the fail instead of nothing ? is the nodejs lib used in production by someone ?

help me plz.

**Comment by rafipiccolo** [comment] 2017-04-12 12:19
The pb seems to be here line 276 in api.js :

`}), function(data) {`

when i add console.log(data) after this line, it contains an error.
This error is visible nowhere outside of the lib......

To reproduce the error i see you can simply put a wrong passphrase.
Please tell me when there will be a patch.

thank you

**Comment by gabriellupu** [comment] 2017-04-12 12:21
Hello @rafipiccolo thanks a lot for your research and interest in solving this issue. We will be working on a fix for this problem, since capturing authentication issues cannot be done, according to the problem you are describing. I will add a test to reproduce this issue and have a fix ASAP.

Thanks!

**Comment by gabriellupu** [comment] 2017-04-12 13:17
Added a PR that should fix the issue you addressed, also [there's a test for it that's reproducing the issue you described](https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/4b9c46707ceffed41f3f0f4d834a1579b3647472/test/services/Tokens.js).
Thanks a lot again for addressing this issue!

**Closed** 2017-04-20 07:58 UTC
