### ISSUE TITLE
Your authorization do not allow you to access to this information

### ISSUE THREAD

**Issue by yns01** [Mangopay/mangopay2-nodejs-sdk#31] opened 2016-10-13 19:40 UTC
Hello,

When I make an API call (user creation, payin whatever) I sometimes get the following error:

```
{ Message: 'Your authorization do not allow you to access to this information',
Type: 'not_authorized',
Id: '3b54f507-6805-49c4-beef-5e92da838c66#1476384039',
Date: 1476384040,
errors: null }

Your authorization do not allow you to access to this information { Message: 'Your authorization do not allow you to access to this information',
Type: 'not_authorized',
 Id: '3b54f507-6805-49c4-beef-5e92da838c66#1476384039',
 Date: 1476384040,
errors: null }
```

On my local environment I had the error every once in a while but when the app is deployed it's way more frequent. Please note that I am using the sandbox for now.

**Comment by hobailey** [comment] 2016-10-19 09:01
Hey @yns01, are you using the latest version of the SDK? From v1.1.0, a fix is included for a known possible authorisation problem. To help with debugging, are you able to record when creating a token, when it expires, and then when you get this error, record what token you were using? It would be a huge help for us (since we don't log the authorization header due to its sensitive nature, so debugging this on our side is quite tricky).

**Comment by yns01** [comment] 2016-10-19 19:55
Thanks @hobailey your for reply. I've updated my SDK yesterday, and for now it seems OK.
However, if it occurs again, how should I process to debug ?

**Comment by hobailey** [comment] 2016-10-20 12:19
OK, good news then. For the debug, could you not try what I previously suggested?

**Comment by gabriellupu** [comment] 2016-10-20 12:29
Also, just for the record, please provide the version of nodejs that you are currently running the SDK on for debugging purposes. Thanks!

**Comment by yns01** [comment] 2016-10-20 20:03
Well tbh, I'm not sure what you mean by 

> are you able to record when creating a token, when it expires, and then when you get this error, record what token you were using?

**Comment by hobailey** [comment] 2016-10-24 17:48
I'll reformulate it, but let me know if it still isn't clear:

1. Generate a token as normal and log its value and when it will expire
2. In your app, add a catch for the "not_authorized" error and log what token you were using (and the datetime)

Since the problem is resolved, I'll close this issue for now, but don't hesitate to let us know if the problem comes back.

**Closed by hobailey** 2016-10-24 17:48 UTC
